# Generated by Django 5.1.2 on 2024-10-10 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concrete', '0001_initial'),
        ('floors', '0001_initial'),
        ('sections', '0001_initial'),
        ('walls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axes', models.CharField(max_length=100)),
                ('concrete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concrete.concrete')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floors.floor')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.section')),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walls.wall')),
            ],
            options={
                'unique_together': {('wall', 'floor', 'section', 'concrete', 'axes')},
            },
        ),
    ]
