# Generated by Django 4.1.3 on 2022-11-17 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Statuses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022,
                            11,
                            17,
                            9,
                            46,
                            34,
                            989605,
                            tzinfo=datetime.timezone.utc,
                        ),
                        verbose_name="Created at",
                    ),
                ),
            ],
        ),
    ]
