# Generated by Django 4.1.3 on 2022-11-17 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuses",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 17, 9, 47, 36, 957720, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
