# Generated by Django 4.1.3 on 2022-11-17 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0002_alter_statuses_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuses",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
